// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Image Handwriting",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Image Handwriting",
            targets: ["AppModule"],
            bundleIdentifier: "vincentspitale.Image-Handwriting",
            teamIdentifier: "R4NGB6G36L",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/hfutrell/BezierKit.git", .exact("0.14.0"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "BezierKit", package: "bezierkit")
            ],
            path: "."
        )
    ]
)